### ISSUE TITLE
[bug] Know more button in cards in event page is not working

### ISSUE THREAD

**Issue by MuhammedFaraz** [WeMakeDevs/wemakedevs#374]
### Describe the bug

The BattleSnake Battleground event link under the past events section is broken or missing.

### To Reproduce

1. Go to wemakedevs.org
2. Click on Events in the below announcement
3. Scroll down to past events section
4. Click on the BattleSnake battleground event
5. See error 404 page on github

### Expected Behavior

The link should work

### Screenshot/ Video

![image](https://user-images.githubusercontent.com/92734739/215292622-576b1e74-9dd9-4d06-b9bc-8a414a7966ed.png)

**Comment by shubhamku044** [comment]
Can I fix this issue?

**Comment by Chandraprakash-Darji** [comment]
@shubhamku044 repo is archived. So I recommend you to remove button of `Know more`

**Comment by Chandraprakash-Darji** [comment]
@MuhammedFaraz Thanks for raising the issue.

**Comment by shubhamku044** [comment]
> @shubhamku044 repo is archived. So I recommend you to remove button of `Know more`

Okay 👍

**Comment by shubhamku044** [comment]
![Screenshot 2023-01-31 at 3 25 47 PM](https://user-images.githubusercontent.com/77788249/215727725-37187f8c-c915-414b-8650-707c450dac21.jpg)
So there is a problem if we remove the `know more` buttons because all the `know more` buttons redirect users to so other links like youtube, cloudnativehack. So instead of removing it. I am updating the events repo battle-snake link to his youtube video of the battle-snake live stream.
